#!/usr/bin/env bash
set -euo pipefail

SERVICE_NAME=${1:-pay-theory-documentation}
OUTPUT_DIR=${2:-build/edge}
EDGE_SOURCE_DIR="edge/markdown-redirect"
MANIFEST_JSON="build/llm-docs/markdown-routes-manifest.json"
ZIP_PATH="${OUTPUT_DIR}/${SERVICE_NAME}-markdown-edge-lambda.zip"

if [[ ! -f "${MANIFEST_JSON}" ]]; then
  echo "Missing ${MANIFEST_JSON}; run npm run build before packaging Lambda@Edge." >&2
  exit 1
fi

if [[ ! -f "${EDGE_SOURCE_DIR}/index.js" ]]; then
  echo "Missing ${EDGE_SOURCE_DIR}/index.js" >&2
  exit 1
fi

TMP_DIR=$(mktemp -d)
cleanup() {
  rm -rf "${TMP_DIR}"
}
trap cleanup EXIT

mkdir -p "${OUTPUT_DIR}"
cp "${EDGE_SOURCE_DIR}/index.js" "${TMP_DIR}/index.js"
cp "${EDGE_SOURCE_DIR}/constants.js" "${TMP_DIR}/constants.js"
cp "${EDGE_SOURCE_DIR}/README.md" "${TMP_DIR}/README.md"

node - "${MANIFEST_JSON}" "${TMP_DIR}/manifest.js" <<'NODE'
const fs = require('node:fs');

const [, , manifestPath, outputPath] = process.argv;
const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));

fs.writeFileSync(
  outputPath,
  [
    '/**',
    ' * Generated by shell/package_markdown_edge_lambda.sh.',
    ' * Do not edit this file inside the Lambda artifact.',
    ' */',
    `module.exports = ${JSON.stringify(manifest, null, 2)};`,
    '',
  ].join('\n'),
);
NODE

rm -f "${ZIP_PATH}"
(
  cd "${TMP_DIR}"
  zip -qr "${OLDPWD}/${ZIP_PATH}" .
)

echo "${ZIP_PATH}"
