// Source-of-truth config for agent-facing documentation artifacts.
// Consumed by scripts/build-agent-docs-artifacts.js and scripts/validate-agent-docs-artifacts.js.
// Do not hand-edit generated build/** outputs; run `npm run agent-docs:build` instead.

const SITE_URL = 'https://docs.paytheory.com';
const LLM_DOCS_PREFIX = '/llm-docs/';
const SOURCE_DOCS_PREFIX = '/llm-docs/source/';

module.exports = {
  siteUrl: SITE_URL,

  defaultVersionGuidance:
    'Use Live docs by default. Use Lab docs only when the user explicitly requests preview or beta behavior.',

  // Routes excluded from agent indexes (nav chrome, search, etc.).
  excludedRoutePatterns: ['/search', '/markdown-page', '/tags'],

  // Curated top-level sections rendered in the concise llms.txt.
  sections: [
    {
      key: 'getting-started',
      title: 'Getting Started',
      description:
        'Quickstart guide, API key setup, error handling, and initial integration steps.',
      representativeRoute: '/docs/main/getting_started/quickstart',
      routePrefix: '/docs/main/getting_started',
    },
    {
      key: 'online-payments',
      title: 'Online Payments',
      description:
        'Payment links, tokenizing payment methods, ACH, cash payments, wallet transactions, and processing transactions.',
      representativeRoute: '/docs/main/online_payments/payment_links',
      routePrefix: '/docs/main/online_payments',
    },
    {
      key: 'recurring-payments',
      title: 'Recurring Payments',
      description:
        'Subscriptions, payment plans, and managing recurring billing.',
      representativeRoute:
        '/docs/main/recurring_payments/create_a_subscription',
      routePrefix: '/docs/main/recurring_payments',
    },
    {
      key: 'invoicing',
      title: 'Invoicing & Billing',
      description: 'Invoice creation, management, and delivery.',
      representativeRoute: '/docs/main/invoicing_and_billing/create_an_invoice',
      routePrefix: '/docs/main/invoicing_and_billing',
    },
    {
      key: 'after-payments',
      title: 'After Payments',
      description:
        'Settlements, disputes, failed transactions, receipts, and post-transaction management.',
      representativeRoute: '/docs/main/after_payments/overview',
      routePrefix: '/docs/main/after_payments',
    },
    {
      key: 'sandbox',
      title: 'Testing & Sandbox',
      description: 'Sandbox environment and testing utilities.',
      representativeRoute: '/docs/main/testing',
      routeExact: '/docs/main/testing',
    },
    {
      key: 'javascript-sdk',
      title: 'JavaScript SDK',
      description:
        'Pay Theory JavaScript SDK reference and integration guides.',
      representativeRoute: '/docs/sdk/javascript/main',
      routePrefix: '/docs/sdk/javascript',
    },
    {
      key: 'apple-sdk',
      title: 'Apple SDK',
      description: 'Pay Theory Apple iOS SDK reference and integration guides.',
      representativeRoute: '/docs/sdk/apple/app_registration',
      routePrefix: '/docs/sdk/apple',
    },
    {
      key: 'android-sdk',
      title: 'Android SDK',
      description: 'Pay Theory Android SDK reference and integration guides.',
      representativeRoute: '/docs/sdk/android/main',
      routePrefix: '/docs/sdk/android',
    },
    {
      key: 'graphql-api',
      title: 'GraphQL API',
      description:
        'Complete Pay Theory GraphQL API reference with all operations, types, and examples.',
      representativeRoute: '/llm-docs/index.md',
      routePrefix: '/docs/api',
      llmDocsPrefix: LLM_DOCS_PREFIX,
    },
    {
      key: 'changelog',
      title: 'Changelog',
      description: 'API and SDK release notes and version history.',
      representativeRoute: '/docs/main/changelog',
      routeExact: '/docs/main/changelog',
    },
  ],

  // Topic index groupings — determines which manifest routes appear in each index file.
  topicIndexes: [
    {
      key: 'guides',
      title: 'Guides',
      filename: 'guides.md',
      routePrefixes: ['/docs/main/'],
      excludePrefixes: [],
    },
    {
      key: 'sdk',
      title: 'SDK Reference',
      filename: 'sdk.md',
      routePrefixes: ['/docs/sdk/'],
      excludePrefixes: [],
    },
    {
      key: 'api',
      title: 'GraphQL API Reference',
      filename: 'api.md',
      routePrefixes: ['/docs/api/'],
      excludePrefixes: [],
    },
    {
      key: 'lab',
      title: 'Lab (Preview)',
      filename: 'lab.md',
      routePrefixes: ['/docs/lab/'],
      excludePrefixes: [],
    },
  ],

  // Public API skill packages generated by graphql-docs.config.js.
  apiSkills: {
    live: {
      name: 'pay-theory-api-skill',
      label: 'Pay Theory API Skill (Live)',
      zipPath: 'docs/api/_data/pay-theory-api-skill.zip',
      zipUrl: `${SITE_URL}/docs/api/_data/pay-theory-api-skill.zip`,
      docsRoute: '/docs/api/agent-skills/pay-theory-api-skill',
    },
    lab: {
      name: 'pay-theory-api-skill-lab',
      label: 'Pay Theory API Skill (Lab)',
      zipUrl: `${SITE_URL}/docs/lab/api/agent-skills/pay-theory-api-skill-lab/pay-theory-api-skill-lab.zip`,
      docsRoute: '/docs/lab/api/agent-skills/pay-theory-api-skill-lab',
    },
  },

  // Paths for generated agent-facing artifacts (all relative to site root).
  llmDocs: {
    manifestPath: '/llm-docs/markdown-routes-manifest.json',
    agentIndexPath: '/llm-docs/agent-index.json',
    llmsTxtPath: '/llms.txt',
    llmsFullTxtPath: '/llms-full.txt',
    indexesBasePath: '/llm-docs/indexes/',
    sourcePath: SOURCE_DOCS_PREFIX,
  },
};
